package vanillafashion.client.outfit;

import java.io.IOException;
import java.nio.*;
import java.nio.file.*;
import java.util.*;
import java.util.zip.CRC32;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.slf4j.helpers.NOPLogger;
import vanillafashion.cape.CapeAssetHash;
import vanillafashion.outfit.*;
import vanillafashion.network.*;
import vanillafashion.fashion.*;
import vanillafashion.client.fashion.ClientPlayerFashionRegistry;
import vanillafashion.client.render.outfit.*;
import vanillafashion.testutil.S03TestAssets;
import static org.junit.jupiter.api.Assertions.*;

class ClientOutfitPipelineTest {
    @TempDir Path temp;
    static final OutfitId ID=new OutfitId("robe");static final UUID SELF=new UUID(0,1);
    static OutfitRegistrySnapshot snapshot(String hash){return new OutfitRegistrySnapshot(true,List.of(new OutfitRegistrySnapshot.Entry(ID,OutfitPart.ALL,Set.of(OutfitModel.WIDE,OutfitModel.SLIM),Map.of(OutfitModel.WIDE,hash,OutfitModel.SLIM,hash))));}
    static Map<OutfitPart,Boolean> visibility(){var result=new EnumMap<OutfitPart,Boolean>(OutfitPart.class);for(var part:OutfitPart.CANONICAL_ORDER)result.put(part,true);return result;}
    static final class Lease implements ClientOutfitTextureManager.OwnedTexture {boolean available=true;int closed;public boolean ready(){return available&&closed==0;}public void close(){closed++;}}
    final ClientOutfitRegistry registry=new ClientOutfitRegistry();final ClientOutfitAssetStore store=new ClientOutfitAssetStore();final ClientOutfitTextureManager textures=new ClientOutfitTextureManager();
    ClientOutfitAssetCache cache(){return new ClientOutfitAssetCache(temp.resolve("cache"),NOPLogger.NOP_LOGGER);}
    @Test void unsupportedUnknownUnavailableAndKnownRemainDistinct(){Object c=new Object();assertEquals(ClientOutfitRegistry.State.UNSUPPORTED,registry.state());registry.begin(c);assertEquals(ClientOutfitRegistry.State.UNKNOWN,registry.state());registry.replace(c,OutfitRegistrySnapshot.unavailable());assertEquals(ClientOutfitRegistry.State.UNAVAILABLE,registry.state());registry.begin(c);registry.replace(c,new OutfitRegistrySnapshot(true,List.of()));assertEquals(ClientOutfitRegistry.State.KNOWN,registry.state());assertTrue(registry.requiredHashes().isEmpty());}
    @Test void conflictingSnapshotDeactivatesAndCannotRecoverUntilNewConnection(){Object c=new Object();registry.begin(c);var initial=snapshot("a".repeat(64));assertEquals(ClientOutfitRegistry.Result.APPLIED,registry.replace(c,initial));assertEquals(ClientOutfitRegistry.Result.IDEMPOTENT,registry.replace(c,initial));assertEquals(ClientOutfitRegistry.Result.CONFLICT,registry.replace(c,snapshot("b".repeat(64))));assertEquals(ClientOutfitRegistry.State.UNAVAILABLE,registry.state());assertTrue(registry.find(ID).isEmpty());assertEquals(ClientOutfitRegistry.Result.CONFLICT,registry.replace(c,initial));Object newer=new Object();registry.begin(newer);assertEquals(ClientOutfitRegistry.Result.STALE,registry.replace(c,initial));assertEquals(ClientOutfitRegistry.Result.APPLIED,registry.replace(newer,initial));}
    @Test void authorizedLateAssetBecomesReadyNextFrameWithoutChangingAuthorityAndModelRolesShareOneTexture(){Object c=new Object();byte[] bytes=S03TestAssets.png();String hash=CapeAssetHash.sha256(bytes);var sync=new ClientOutfitAssetSync(registry,store,cache());sync.begin(c);textures.begin(c);sync.snapshot(c,snapshot(hash));
        var authority=new ClientPlayerFashionRegistry();authority.beginConnection(c);var parts=OutfitSelections.original().with(OutfitPart.HEAD,OutfitPartSelection.outfit(ID));var state=new FullPlayerFashionState(new PlayerFashionStoredState(Optional.empty(),parts),new PlayerFashionEffectiveState(Optional.empty(),parts),8);authority.receiveFullSnapshot(c,new FullPlayerFashionSnapshot(true,List.of(new FullPlayerFashionEntry(SELF,state))));
        var resolver=new ClientOutfitTextureResolver(registry,store,textures);var provider=new NetworkOutfitAppearanceProvider(authority,resolver);var world=new OutfitAppearanceProvider.Context(c,SELF,OutfitModel.WIDE,OutfitRenderAppearance.Scene.WORLD,visibility());
        assertTrue(provider.resolve(world).orElseThrow().asset(OutfitPart.HEAD).orElseThrow().texture().isEmpty());var request=sync.missing(c).getFirst();sync.markRequested(c,request);assertEquals(ClientOutfitAssetSync.Receive.STORED,sync.receive(c,new OutfitAssetDataPayload(hash,bytes)));
        Lease lease=new Lease();int[] uploads={0};ClientOutfitTextureManager.Backend backend=(id,png)->{uploads[0]++;assertArrayEquals(bytes,png);return lease;};assertEquals(ClientOutfitTextureManager.Result.REGISTERED,textures.register(c,store,hash,backend,NOPLogger.NOP_LOGGER));assertEquals(ClientOutfitTextureManager.Result.ALREADY_REGISTERED,textures.register(c,store,hash,backend,NOPLogger.NOP_LOGGER));assertEquals(1,uploads[0]);
        var wide=resolver.resolve(c,ID,OutfitModel.WIDE).orElseThrow().texture();var slim=resolver.resolve(c,ID,OutfitModel.SLIM).orElseThrow().texture();assertEquals(wide,slim);assertEquals(ClientOutfitTextureManager.identifierFor(hash),wide.orElseThrow());assertTrue(provider.resolve(world).orElseThrow().asset(OutfitPart.HEAD).orElseThrow().texture().isPresent());assertEquals(state,authority.fullAuthority(SELF).orElseThrow());
        for(var scene:OutfitRenderAppearance.Scene.values()){var context=new OutfitAppearanceProvider.Context(c,SELF,OutfitModel.SLIM,scene,visibility());var appearance=provider.resolve(context).orElseThrow();assertEquals(parts,appearance.selections());assertEquals(scene,appearance.scene());assertEquals(SELF,appearance.player());}
        assertTrue(provider.resolve(new OutfitAppearanceProvider.Context(c,new UUID(0,2),OutfitModel.WIDE,OutfitRenderAppearance.Scene.WORLD,visibility())).isEmpty());
        // 受控 backend 模拟资源重载期间暂不可用，验证 ready 与所有权；真实 GPU 重载由 Runtime 判定。
        lease.available=false;assertTrue(textures.find(c,hash).isEmpty());lease.available=true;assertEquals(wide,textures.find(c,hash));assertEquals(1,uploads[0]);assertEquals(0,lease.closed);
    }
    @Test void invalidOrUnrequestedDataCannotEnterStoreCacheOrGpu() throws Exception{Object c=new Object();byte[] good=S03TestAssets.png();String hash=CapeAssetHash.sha256(good);var cache=cache();var sync=new ClientOutfitAssetSync(registry,store,cache);sync.begin(c);sync.snapshot(c,snapshot(hash));assertEquals(ClientOutfitAssetSync.Receive.NOT_REQUESTED,sync.receive(c,new OutfitAssetDataPayload(hash,good)));sync.markRequested(c,sync.missing(c).getFirst());assertEquals(ClientOutfitAssetSync.Receive.INVALID,sync.receive(c,new OutfitAssetDataPayload(hash,new byte[]{1})));assertEquals(0,store.size());assertTrue(sync.missing(c).isEmpty());assertFalse(Files.exists(cache.pathFor(hash)));assertEquals(ClientOutfitAssetSync.Receive.NOT_AUTHORIZED,sync.receive(c,new OutfitAssetDataPayload("a".repeat(64),good)));}
    @ParameterizedTest @ValueSource(ints={0,65537}) void storeRejectsOutOfRangeBeforeDecode(int size){assertEquals(ClientOutfitAssetStore.Result.INVALID_SIZE,store.store("a".repeat(64),new byte[size]));}
    @Test void wrongPngRoleBadCrcAndHugeIhdrRejected(){byte[] cape=S03TestAssets.png(64,32,0xff123456);assertEquals(ClientOutfitAssetStore.Result.INVALID_DIMENSIONS,store.store(CapeAssetHash.sha256(cape),cape));byte[] bad=S03TestAssets.png();bad[bad.length-1]^=1;assertEquals(ClientOutfitAssetStore.Result.INVALID_PNG,store.store(CapeAssetHash.sha256(bad),bad));byte[] huge=S03TestAssets.png();ByteBuffer.wrap(huge).putInt(16,Integer.MAX_VALUE);assertEquals(ClientOutfitAssetStore.Result.INVALID_DIMENSIONS,store.store(CapeAssetHash.sha256(huge),huge));}
    @Test void cachedContentNeedsCurrentSnapshotAndFullRevalidation() throws Exception{Object c=new Object();byte[] bytes=S03TestAssets.png();String hash=CapeAssetHash.sha256(bytes);var cache=cache();cache.storeValidated(hash,bytes);var sync=new ClientOutfitAssetSync(registry,store,cache);sync.begin(c);assertEquals(0,store.size());sync.snapshot(c,snapshot("b".repeat(64)));assertEquals(0,store.size());sync.disconnect(c);sync.begin(c);sync.snapshot(c,snapshot(hash));assertTrue(store.contains(hash));assertTrue(sync.missing(c).isEmpty());sync.disconnect(c);assertTrue(Files.exists(cache.pathFor(hash)));
        Files.write(cache.pathFor(hash),new byte[]{1,2,3});sync.begin(c);sync.snapshot(c,snapshot(hash));assertEquals(0,store.size());assertEquals(1,sync.missing(c).size());assertFalse(Files.exists(cache.pathFor(hash)));}
    @Test void oldConnectionDataAndCleanupCannotDestroyNewTextureOrPopulateNewStore(){Object old=new Object(),next=new Object();byte[] bytes=S03TestAssets.png();String hash=CapeAssetHash.sha256(bytes);var sync=new ClientOutfitAssetSync(registry,store,cache());sync.begin(old);textures.begin(old);sync.snapshot(old,snapshot(hash));sync.markRequested(old,sync.missing(old).getFirst());sync.receive(old,new OutfitAssetDataPayload(hash,bytes));Lease oldLease=new Lease();textures.register(old,store,hash,(id,png)->oldLease,NOPLogger.NOP_LOGGER);
        sync.begin(next);textures.begin(next);assertEquals(1,oldLease.closed);sync.snapshot(next,snapshot(hash));Lease nextLease=new Lease();textures.register(next,store,hash,(id,png)->nextLease,NOPLogger.NOP_LOGGER);assertFalse(sync.disconnect(old));assertFalse(textures.disconnect(old));assertEquals(ClientOutfitAssetSync.Receive.STALE,sync.receive(old,new OutfitAssetDataPayload(hash,bytes)));assertEquals(0,nextLease.closed);assertTrue(textures.find(next,hash).isPresent());assertTrue(textures.disconnect(next));assertEquals(1,nextLease.closed);assertFalse(textures.disconnect(next));}
    @Test void failedRegistrationReleasesOwnedResourceAndDoesNotAdvertiseFakeReady(){Object c=new Object();byte[] bytes=S03TestAssets.png();String hash=CapeAssetHash.sha256(bytes);store.store(hash,bytes);textures.begin(c);Lease lease=new Lease();lease.available=false;int[] calls={0};ClientOutfitTextureManager.Backend backend=(id,png)->{calls[0]++;return lease;};assertEquals(ClientOutfitTextureManager.Result.FAILED,textures.register(c,store,hash,backend,NOPLogger.NOP_LOGGER));assertEquals(1,lease.closed);assertTrue(textures.find(c,hash).isEmpty());textures.register(c,store,hash,backend,NOPLogger.NOP_LOGGER);assertEquals(1,calls[0]);}
    @Test void singleModelSupportAndBadDeclaredSiblingStayDistinguishable(){Object c=new Object();registry.begin(c);registry.replace(c,new OutfitRegistrySnapshot(true,List.of(new OutfitRegistrySnapshot.Entry(ID,Set.of(OutfitPart.HEAD),Set.of(OutfitModel.WIDE),Map.of()))));var resolver=new ClientOutfitTextureResolver(registry,store,textures);assertTrue(resolver.resolve(c,ID,OutfitModel.SLIM).isEmpty());var wide=resolver.resolve(c,ID,OutfitModel.WIDE).orElseThrow();assertTrue(wide.texture().isEmpty());assertEquals(Set.of(OutfitPart.HEAD),wide.metadata().parts());assertTrue(registry.requiredHashes().isEmpty());}
    @Test void devOverrideIsExclusiveAndDoesNotFallThroughToProduction(){OutfitAppearanceProvider production=c->{throw new AssertionError("开发覆盖不应同时调用正式来源。");};OutfitAppearanceProvider override=c->Optional.empty();assertSame(override,NetworkOutfitAppearanceProvider.exclusive(production,override));assertSame(production,NetworkOutfitAppearanceProvider.exclusive(production,OutfitAppearanceProvider.EMPTY));}
    @Test void full512AssetColdCacheKeeps32MiBOriginalByteBoundAndBatchesOf64(){Object c=new Object();var contents=new LinkedHashMap<String,byte[]>();var entries=new ArrayList<OutfitRegistrySnapshot.Entry>();for(int i=0;i<256;i++){var hashes=new EnumMap<OutfitModel,String>(OutfitModel.class);for(var model:OutfitModel.CANONICAL_ORDER){byte[] bytes=paddedPng(i*2+model.ordinal());String hash=CapeAssetHash.sha256(bytes);contents.put(hash,bytes);hashes.put(model,hash);}entries.add(new OutfitRegistrySnapshot.Entry(new OutfitId("robe_"+i),OutfitPart.ALL,Set.of(OutfitModel.WIDE,OutfitModel.SLIM),hashes));}
        var sync=new ClientOutfitAssetSync(registry,store,cache());sync.begin(c);sync.snapshot(c,new OutfitRegistrySnapshot(true,entries));var requests=sync.missing(c);assertEquals(8,requests.size());for(var request:requests){assertEquals(64,request.sha256Hashes().size());sync.markRequested(c,request);for(String hash:request.sha256Hashes())assertEquals(ClientOutfitAssetSync.Receive.STORED,sync.receive(c,new OutfitAssetDataPayload(hash,contents.get(hash))));}assertEquals(512,store.size());assertEquals(0,sync.pendingCount());assertTrue(sync.missing(c).isEmpty());assertEquals(33554432L,contents.values().stream().mapToLong(a->a.length).sum());}
    static byte[] paddedPng(int index){byte[] base=S03TestAssets.png(64,64,0xff000000|index);int length=65536-base.length-12;byte[] out=new byte[65536];int offset=base.length-12;System.arraycopy(base,0,out,0,offset);ByteBuffer data=ByteBuffer.wrap(out);data.putInt(offset,length);data.putInt(offset+4,0x76704167);CRC32 crc=new CRC32();crc.update(out,offset+4,length+4);data.putInt(offset+8+length,(int)crc.getValue());System.arraycopy(base,offset,out,offset+12+length,12);assertEquals(OutfitPngValidator.Result.VALID,OutfitPngValidator.validate(out));return out;}
}
