package dev.zbw3790.fashion.cape;

public enum CapeValidationErrorCode {
	INVALID_ID,
	NOT_A_DIRECTORY,
	MISSING_CAPE,
	ASSET_LAYOUT_CONFLICT,
	SHARED_NOT_REGULAR_FILE,
	SHARED_FILE_TOO_LARGE,
	INVALID_SHARED_PNG,
	INVALID_SHARED_DIMENSIONS,
	CAPE_NOT_REGULAR_FILE,
	ELYTRA_NOT_REGULAR_FILE,
	CAPE_FILE_TOO_LARGE,
	ELYTRA_FILE_TOO_LARGE,
	INVALID_CAPE_PNG,
	INVALID_ELYTRA_PNG,
	INVALID_CAPE_DIMENSIONS,
	INVALID_ELYTRA_DIMENSIONS,
	IO_ERROR
}
