package vanillafashion.client.fashion;

import java.util.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;
import vanillafashion.cape.CapeId;
import vanillafashion.fashion.*;
import vanillafashion.outfit.*;
import vanillafashion.network.*;
import vanillafashion.client.network.*;
import vanillafashion.client.screen.WardrobeSelectionSession;
import static org.junit.jupiter.api.Assertions.*;

class ClientFullFashionStateTest {
    static final UUID SELF=new UUID(0,1),OTHER=new UUID(0,2);static final CapeId A=new CapeId("a"),B=new CapeId("b"),C=new CapeId("c");
    static FullPlayerFashionState state(long revision,CapeId cape,OutfitSelections outfit){var stored=new PlayerFashionStoredState(Optional.ofNullable(cape),outfit);return new FullPlayerFashionState(stored,new PlayerFashionEffectiveState(stored.cape(),outfit),revision);}
    static FullPlayerFashionState state(long revision,CapeId cape){return state(revision,cape,OutfitSelections.original());}
    static ClientPlayerFashionRegistry ready(Object connection,FullPlayerFashionState initial){var registry=new ClientPlayerFashionRegistry();registry.beginConnection(connection);registry.receiveFullSnapshot(connection,new FullPlayerFashionSnapshot(true,List.of(new FullPlayerFashionEntry(SELF,initial))));return registry;}
    @Test void v2RouteIgnoresAllLegacyAuthorityWritesAndProjectsOneCapeTruth(){Object connection=new Object();var r=ready(connection,state(3,A));r.replace(new PlayerFashionSnapshot(true,List.of(new PlayerFashionEntry(SELF,PlayerFashionAuthoritativeState.active(B)))));r.update(new PlayerFashionEntry(SELF,PlayerFashionAuthoritativeState.active(C)));r.remove(SELF);r.confirmSelfResult(SELF,PlayerFashionAuthoritativeState.active(B));assertEquals(FashionAuthorityRoute.V2,r.route());assertEquals(Optional.of(A),r.getStoredSelection(SELF));assertEquals(state(3,A),r.fullAuthority(SELF).orElseThrow());}
    @Test void legacyRouteNeverActivatesOutfitAuthority(){Object c=new Object();var r=new ClientPlayerFashionRegistry();r.beginConnection(c);r.replace(new PlayerFashionSnapshot(true,List.of(new PlayerFashionEntry(SELF,PlayerFashionAuthoritativeState.active(A)))));r.receiveFullSnapshot(c,new FullPlayerFashionSnapshot(true,List.of(new FullPlayerFashionEntry(SELF,state(2,B)))));assertEquals(FashionAuthorityRoute.LEGACY,r.route());assertTrue(r.fullAuthority(SELF).isEmpty());assertEquals(Optional.of(A),r.getEffectiveSelection(SELF));}
    @Test void orderedUpdatesRejectLowerAndStopOnEqualRevisionConflict(){Object c=new Object();var r=ready(c,state(3,A));assertEquals(ClientFullPlayerFashionRegistry.Acceptance.STALE,r.receiveFullUpdate(c,new FullPlayerFashionEntry(SELF,state(2,B))));assertEquals(ClientFullPlayerFashionRegistry.Acceptance.IDEMPOTENT,r.receiveFullUpdate(c,new FullPlayerFashionEntry(SELF,state(3,A))));assertEquals(ClientFullPlayerFashionRegistry.Acceptance.PROTOCOL_ERROR,r.receiveFullUpdate(c,new FullPlayerFashionEntry(SELF,state(3,B))));assertEquals(ClientPlayerFashionRegistry.State.UNAVAILABLE,r.state());assertTrue(r.fullAuthority(SELF).isEmpty());r.receiveFullSnapshot(c,new FullPlayerFashionSnapshot(true,List.of(new FullPlayerFashionEntry(SELF,state(4,C)))));assertTrue(r.fullAuthority(SELF).isEmpty());}
    @Test void leftThenJoinZeroAndSnapshotReplacementNeedNoTombstone(){Object c=new Object();var r=ready(c,state(100,A));r.receiveFullRemove(c,new FullPlayerFashionRemovePayload(SELF,100,FullPlayerFashionRemovePayload.Reason.LEFT));assertTrue(r.fullAuthority(SELF).isEmpty());r.receiveFullUpdate(c,new FullPlayerFashionEntry(SELF,state(0,B)));assertEquals(0,r.fullAuthority(SELF).orElseThrow().revision());r.receiveFullUpdate(c,new FullPlayerFashionEntry(SELF,state(3,C)));r.receiveFullSnapshot(c,new FullPlayerFashionSnapshot(true,List.of(new FullPlayerFashionEntry(SELF,state(0,A)))));assertEquals(state(0,A),r.fullAuthority(SELF).orElseThrow());}
    @Test void defaultKeepsKnownOnlineEntryAndStaleLeftCannotEraseIt(){Object c=new Object();var r=ready(c,state(4,A));r.receiveFullRemove(c,new FullPlayerFashionRemovePayload(SELF,5,FullPlayerFashionRemovePayload.Reason.DEFAULT));assertEquals(FullPlayerFashionState.defaults(5),r.fullAuthority(SELF).orElseThrow());r.receiveFullRemove(c,new FullPlayerFashionRemovePayload(SELF,4,FullPlayerFashionRemovePayload.Reason.LEFT));assertEquals(1,r.size());}
    @Test void oldConnectionCleanupUpdatesAndSameNumericRequestAreRejected(){Object old=new Object(),next=new Object();var r=ready(old,state(0,A));assertEquals(1,r.fullRequests().allocate().orElseThrow());r.beginConnection(next);r.receiveFullSnapshot(next,new FullPlayerFashionSnapshot(true,List.of(new FullPlayerFashionEntry(SELF,state(0,B)))));assertEquals(1,r.fullRequests().allocate().orElseThrow());assertFalse(r.disconnect(old));r.receiveFullUpdate(old,new FullPlayerFashionEntry(SELF,state(50,C)));assertFalse(ClientFullFashionSelectionResults.apply(old,old,SELF,new FullFashionSelectionResultPayload(1,FullFashionSelectionStatus.SUCCESS,Optional.of(state(1,C))),r,()->null));assertTrue(r.fullRequests().hasOutstanding());assertEquals(state(0,B),r.fullAuthority(SELF).orElseThrow());}
    @Test void resultDoesNotUpgradeUnavailableWorldSnapshot(){Object c=new Object();var r=ready(c,state(0,A));r.receiveFullSnapshot(c,FullPlayerFashionSnapshot.unavailable());r.full().result(c,new FullPlayerFashionEntry(SELF,state(1,B)));assertEquals(ClientPlayerFashionRegistry.State.UNAVAILABLE,r.state());assertTrue(r.fullAuthority(SELF).isEmpty());assertEquals(state(1,B),r.fullSelfAuthority(SELF).orElseThrow());}
    @Test void ownUpdateBeforeSuccessDoesNotLeaveAConflictAndCanApplyAgain(){Object c=new Object();var r=ready(c,state(0,null));var screen=new WardrobeSelectionSession();screen.observeFull(r.fullSelfAuthority(SELF),r.state());screen.select(Optional.of(A));var request=screen.finishFull(r.fullRequests(),true,id->true).orElseThrow();r.receiveFullUpdate(c,new FullPlayerFashionEntry(SELF,state(1,A)));screen.observeFull(r.fullSelfAuthority(SELF),r.state());assertTrue(screen.conflict());assertFalse(screen.canEdit());ClientFullFashionSelectionResults.apply(c,c,SELF,new FullFashionSelectionResultPayload(request.requestId(),FullFashionSelectionStatus.SUCCESS,Optional.of(state(1,A))),r,()->screen);assertFalse(screen.conflict());assertFalse(screen.dirty());assertTrue(screen.canEdit());screen.select(Optional.of(B));assertEquals(2,screen.finishFull(r.fullRequests(),true,id->true).orElseThrow().requestId());}
    @Test void matchingLowRevisionResultSettlesPendingWithoutRollingBackNewerGlobalOrScreen(){Object c=new Object();var r=ready(c,state(0,null));var screen=new WardrobeSelectionSession();screen.observeFull(r.fullSelfAuthority(SELF),r.state());screen.select(Optional.of(A));screen.finishFull(r.fullRequests(),true,id->true);r.receiveFullUpdate(c,new FullPlayerFashionEntry(SELF,state(2,B)));assertTrue(ClientFullFashionSelectionResults.apply(c,c,SELF,new FullFashionSelectionResultPayload(1,FullFashionSelectionStatus.SUCCESS,Optional.of(state(1,A))),r,()->screen));assertEquals(state(2,B),r.fullAuthority(SELF).orElseThrow());assertEquals(Optional.of(B),screen.baseline());assertEquals(Optional.of(B),screen.draft());assertFalse(r.fullRequests().hasOutstanding());assertEquals(0,screen.pendingRequestId());}
    @Test void closedScreenLateResultUpdatesGlobalWithoutReopeningOrReleasingAnotherRequest(){Object c=new Object();var r=ready(c,state(0,null));var screen=new WardrobeSelectionSession();screen.observeFull(r.fullSelfAuthority(SELF),r.state());screen.select(Optional.of(A));screen.finishFull(r.fullRequests(),true,id->true);screen.cancel();ClientFullFashionSelectionResults.apply(c,c,SELF,new FullFashionSelectionResultPayload(1,FullFashionSelectionStatus.SUCCESS,Optional.of(state(1,A))),r,()->null);assertTrue(screen.closed());assertEquals(Optional.of(A),r.getStoredSelection(SELF));assertEquals(2,r.fullRequests().allocate().orElseThrow());assertFalse(ClientFullFashionSelectionResults.apply(c,c,SELF,new FullFashionSelectionResultPayload(1,FullFashionSelectionStatus.SUCCESS,Optional.of(state(1,A))),r,()->null));assertTrue(r.fullRequests().hasOutstanding());}
    @Test void capeBridgeMergesNewOutfitFieldsAndUsesCurrentRevision(){Object c=new Object();var r=ready(c,state(0,null));var screen=new WardrobeSelectionSession();screen.observeFull(r.fullSelfAuthority(SELF),r.state());screen.select(Optional.of(A));var outfit=OutfitSelections.original().with(OutfitPart.HEAD,OutfitPartSelection.NONE);r.receiveFullUpdate(c,new FullPlayerFashionEntry(SELF,state(1,null,outfit)));screen.observeFull(r.fullSelfAuthority(SELF),r.state());var request=screen.finishFull(r.fullRequests(),true,id->true).orElseThrow();assertEquals(outfit,request.stored().outfit());assertEquals(Optional.of(A),request.stored().cape());assertEquals(1,request.expectedRevision());}
    @Test void capeBridgeConflictsEvenWhenExternalCapeEqualsDraft(){var screen=new WardrobeSelectionSession();screen.observeFull(Optional.of(state(0,null)),ClientPlayerFashionRegistry.State.AVAILABLE);screen.select(Optional.of(A));screen.observeFull(Optional.of(state(1,A)),ClientPlayerFashionRegistry.State.AVAILABLE);assertTrue(screen.conflict());assertFalse(screen.canFinish(true,false,id->true));assertTrue(screen.status(true,false,id->true).contains("存在外部修改"));}
    @ParameterizedTest @EnumSource(OutfitPart.class) void eachPartUsesThreeWayMergeAndPreservesExplicitConflict(OutfitPart part){var old=state(0,null);var draft=new FullFashionDraft(old);var selected=old.stored().outfit().with(part,OutfitPartSelection.NONE);draft.edit(new PlayerFashionStoredState(Optional.of(A),selected));var external=state(1,null,selected);draft.observe(external);assertEquals(Set.of(FullFashionDraft.Field.values()[part.ordinal()+1]),draft.conflicts());assertEquals(Optional.of(A),draft.draft().cape());assertFalse(draft.canSubmit());}
    @Test void trackerNeverWrapsOrTreatsTimeoutAsCancellation() throws Exception{var tracker=new ClientFullFashionRequestTracker();tracker.begin(new Object());var field=ClientFullFashionRequestTracker.class.getDeclaredField("lastId");field.setAccessible(true);field.setLong(tracker,Long.MAX_VALUE);assertTrue(tracker.allocate().isEmpty());var screen=new WardrobeSelectionSession();Object c=new Object();tracker.begin(c);screen.observeFull(Optional.of(state(0,null)),ClientPlayerFashionRegistry.State.AVAILABLE);screen.select(Optional.of(A));screen.finishFull(tracker,true,id->true);for(int i=0;i<500;i++)screen.tick();assertTrue(tracker.hasOutstanding());assertTrue(screen.status(true,true,id->true).contains("尚未收到"));assertFalse(screen.canEdit());}
    @Test void failureKeepsDraftAndMergesExternalUneditedFields(){Object c=new Object();var r=ready(c,state(0,null));var screen=new WardrobeSelectionSession();screen.observeFull(r.fullSelfAuthority(SELF),r.state());screen.select(Optional.of(A));screen.finishFull(r.fullRequests(),true,id->true);var parts=OutfitSelections.original().with(OutfitPart.LEFT_ARM,OutfitPartSelection.NONE);ClientFullFashionSelectionResults.apply(c,c,SELF,new FullFashionSelectionResultPayload(1,FullFashionSelectionStatus.CONFLICT,Optional.of(state(1,null,parts))),r,()->screen);assertEquals(Optional.of(A),screen.draft());assertEquals(0,screen.pendingRequestId());var next=screen.finishFull(r.fullRequests(),true,id->true).orElseThrow();assertEquals(parts,next.stored().outfit());assertEquals(1,next.expectedRevision());}
}
